- hosts:  "{{host}}"
  user: "{{user}}"
  vars:
     
  tasks:
     - name: docker pull
       command: docker pull "{{image}}"
     - name: docker run
       command: docker run -d --net=host -e "CLUSTER_INFO={{CLUSTER_INFO}}" "{{image}}"
