- hosts:  "{{host}}"
  user: "{{user}}"
  vars:
     
  tasks:
     - name: docker change master
       command: docker exec -it {{container_name}} /bin/bash
       command: /bin/mysql -uroot -p123456 --socket=/percona/mysqld-{{port}}.sock
       command: STOP SLAVE;
       command: RESET MASTER;
       command: RESET SLAVE;
